export const SliderData = [
    {
      image:
        'https://images.turo.com/media/vehicle/images/YXL2IuXmSGOmf6CVxCRslw.1440x700.jpg'
    },
    {
      image:
        'https://images.turo.com/media/vehicle/images/pdpXFR6_R0CgarHVeYeXxg.1440x700.jpg'
    },
    {
      image:
        'https://images.turo.com/media/vehicle/images/z0Ta1V8DRcWC409BJ037Gg.1440x700.jpg'
    },
    {
      image:
        'https://images.turo.com/media/vehicle/images/7ERkJQoUS5aN5G5yoT7fkQ.1440x700.jpg'
    },
    {
      image:
        'https://images.turo.com/media/vehicle/images/4iRmI9q0QA6UTN3A5tUm-g.1440x700.jpg'
    }
  ];